---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: crawler
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: crawler
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/search-engine-crawler:{{ .Values.image.tag }}"
        name: crawler
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MONGO
          value: {{  .Values.mongoHOST | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_POR
          value: {{  .Values.mongoPORT | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{  .Values.rmqHOST | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_USERNAME
          value: {{  .Values.rmqUSERNAME }}
        - name: RMQ_PASSWORD
          value: {{  .Values.rmqPASSWORD }}
        - name: RMQ_QUEUE
          value: {{  .Values.rmqQUEUE }}
        - name: URL
          value: {{  .Values.URL }}
        - name: EXCLUDE_URLS
          value: {{  .Values.EXCLUDE_URLS }}
