---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: crawler
    component: crawler
    release: {{ .Release.Name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector: 
    app: crawler
    component: crawler
    release: {{ .Release.Name }}
