{{ if eq .Release.Namespace "production" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-rabbit-disk
  labels:
    app: rabbit
spec:
  capacity: 
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: /mnt/nfs/rabbit
    server: 10.240.0.150
{{ end }}
